### PR TITLE
adds support for .md files, can parse h tags, bold, italics, links and scratched

### PR DESCRIPTION
**Pull request by ritikbheda**

### CODE REVIEW

**Comment by ritikbheda** [comment]
fixes #9

**Comment by dhillonks** [comment]
Looks good and works for `.md` files. However, I found a few issues while testing, please look into the following:

### 1. Paragraphs not generating properly
Most syntax guides ([markdownguide](https://www.markdownguide.org/basic-syntax/#paragraphs-1), pandoc, github etc) all create paragraph tags for content separated for blank lines. For example: The two paragraphs below should be rendered with `<p>` tags
image
Also, text directly below a heading (h1..h6) should also be contained within `<p>` tags.

### 2. Use `<strong>` instead of `<b>`
Right now, bold text is rendered using the `<b>` tag. However, in accordance with most syntax guides, `<strong>` tags should be instead.
image

### 3. Use `<em>` instead of `<i>`
Right now, italic text is rendered using the `<i>` tag. However, in accordance with most syntax guides, `<em>` tags should be used instead.
image

### 4. Direct links not working
Currently, inline links work properly however, it fails to render automatic links. As per the [syntax guides](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses), urls enclosed within angle brackets `<>` should be rendered as links. For example:
image

## To-do:
- [ ] Fix paragraph generation
- [ ] Use strong tags for bold text
- [ ] Use em tags for italic text
- [ ] Add ability to render automatic links

**Review by dhillonks — CHANGES_REQUESTED** [review]
Looks good and works for `.md` files. However, I found a few issues while testing, please look into the following:

### 1. Paragraphs not generating properly
Most syntax guides ([markdownguide](https://www.markdownguide.org/basic-syntax/#paragraphs-1), pandoc, github etc) all create paragraph tags for content separated for blank lines. For example: The two paragraphs below should be rendered with `<p>` tags
image
Also, text directly below a heading (h1..h6) should also be contained within `<p>` tags.

### 2. Use `<strong>` instead of `<b>`
Right now, bold text is rendered using the `<b>` tag. However, in accordance with most syntax guides, `<strong>` tags should be used instead.
image

### 3. Use `<em>` instead of `<i>`
Right now, italic text is rendered using the `<i>` tag. However, in accordance with most syntax guides, `<em>` tags should be used instead.
image

### 4. Direct links not working
Currently, inline links work properly however, it fails to render automatic links. As per the [syntax guides](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses), urls enclosed within angle brackets `<>` should be rendered as links. For example:
image

## To-do:
- [ ] Fix paragraph generation
- [ ] Use strong tags for bold text
- [ ] Use em tags for italic text
- [ ] Add ability to render automatic links

**Comment by ritikbheda** [comment]
solved in commit 78c4a
fixes #9 
Note: I dont know why i cannot check the toDo list. But all of the points are covered in the above commit

**Review by dhillonks — APPROVED** [review]
Looks good with the recent changes, could you also please modify the `readme.md` to include the `.md`. support in the Features.

**Pull request merged**
